//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KYSv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IzinTalebi
    {
        public int IzinID { get; set; }
        public int UserID { get; set; }
        public string userFirstName { get; set; }
        public string userLastName { get; set; }
        public string userEmail { get; set; }
        public string Message { get; set; }
    
        public virtual IzinTalebi IzinTalebi1 { get; set; }
        public virtual IzinTalebi IzinTalebi2 { get; set; }
        public virtual user user { get; set; }
    }
}
