//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KYSv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class projects
    {
        public int id { get; set; }
        public string ProjectName { get; set; }
        public string ProjectPath { get; set; }
        public bool isActive { get; set; }
    }
}
