//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KYSv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shift
    {
        public int shiftID { get; set; }
        public int userID { get; set; }
        public System.DateTime shiftDate { get; set; }
        public System.TimeSpan shiftLogin { get; set; }
        public System.TimeSpan shiftOut { get; set; }
        public int shiftSum { get; set; }
    
        public virtual user user { get; set; }
    }
}
